### PR TITLE
updated v0.7.0

### LINKED ISSUE #5: Autotick bot did not kicked in for v0.7.0
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Recipe should be re-rendered for v0.7.0

### PR DESCRIPTION
**Pull request by sdebionne**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #5

### CODE REVIEW

**Comment by sdebionne** [comment]
@conda-forge-admin, please rerender

**Comment by sdebionne** [comment]
@conda-forge-admin, please rerender

**Review by ericpre — COMMENTED** [review]
Thanks @sdebionne, looks good! As mentioned in https://github.com/conda-forge/sphinxcontrib-mermaid-feedstock/issues/5#issuecomment-869621645, if there is no reason to use github, I think that we should keep using pypi as source.

**Comment by sdebionne** [comment]
The reason is I could not find the source from `https://pypi.io` -it was not uploaded for this version.  Maybe we could ask the pypi package maintainer why...

**Comment by ericpre** [comment]
Ah, yes, you are right, I have checked that the 0.7 release was on pypi, but [there is only the wheel and not the tarball](https://pypi.org/project/sphinxcontrib-mermaid/0.7/#files). This may explain why the bot didn't make a PR!

Yes, it would good to ask the maintainer, it may be simply that they forgot to upload it. Shall we wait to get an answer from the maintainer?

**Comment by sdebionne** [comment]
> Shall we wait to get an answer from the maintainer?

Sure. Did you contact him, or shall I do it?

**Comment by ericpre** [comment]
Let's merge this PR; once we get an update from @mgaitan in https://github.com/mgaitan/sphinxcontrib-mermaid/issues/75 and the source distribution are available on pypi, we can switch back to pypi.

**Pull request merged**
